import { Activity, ChartNetwork, Clock, Hourglass, MapPin } from "lucide-react";

export const MessageMomentStatsCardsData = [
  {
    stats: 1,
    bgColor: "#4CAF50",
    icon: <Activity />,
    title: "Active Users",
    detail: "12000",
  },

  {
    stats: 2,
    bgColor: "#42A5F5",
    icon: <ChartNetwork />,
    title: "Active Sessions",
    detail: "459",
  },

  {
    stats: 3,
    bgColor: "#FF6B6B",
    icon: <MapPin />,
    title: "Locations",
    detail: "34",
  },

  {
    stats: 4,
    bgColor: "#FFB74D",
    icon: <Hourglass />,
    title: "Avg. Duration",
    detail: "34m 44s",
  },

  {
    stats: 5,
    bgColor: "#AB47BC",
    icon: <Clock />,
    title: "Avg. Expiry Time",
    detail: "145",
  },
];

export const RealTimeMapActivityData = [
  // Pakistan - Sessions
  {
    sessionId: 1,
    userNo: 1,
    isSessionCreator: true,
    country: "Pakistan",
    countryCode: "PK",
    city: "Karachi",
    cityCode: "KHI",
    longitude: 67.0011,
    latitude: 24.8607,
  },

  {
    sessionId: 1,
    userNo: 2,
    isSessionCreator: false,
    country: "Pakistan",
    countryCode: "PK",
    city: "Karachi",
    cityCode: "KHI",
    longitude: 67.0023,
    latitude: 24.8615,
  },

  {
    sessionId: 1,
    userNo: 3,
    isSessionCreator: false,
    country: "Pakistan",
    countryCode: "PK",
    city: "Karachi",
    cityCode: "KHI",
    longitude: 67.0045,
    latitude: 24.8621,
  },

  {
    sessionId: 2,
    userNo: 4,
    isSessionCreator: true,
    country: "Pakistan",
    countryCode: "PK",
    city: "Lahore",
    cityCode: "LHE",
    longitude: 74.3587,
    latitude: 31.5497,
  },

  {
    sessionId: 2,
    userNo: 5,
    isSessionCreator: false,
    country: "Pakistan",
    countryCode: "PK",
    city: "Lahore",
    cityCode: "LHE",
    longitude: 74.3572,
    latitude: 31.55,
  },

  {
    sessionId: 2,
    userNo: 6,
    isSessionCreator: false,
    country: "Pakistan",
    countryCode: "PK",
    city: "Islamabad",
    cityCode: "ISB",
    longitude: 73.0479,
    latitude: 33.6844,
  },

  // India - Sessions
  {
    sessionId: 3,
    userNo: 7,
    isSessionCreator: true,
    country: "India",
    countryCode: "IN",
    city: "Delhi",
    cityCode: "DEL",
    longitude: 77.209,
    latitude: 28.6139,
  },

  {
    sessionId: 3,
    userNo: 8,
    isSessionCreator: false,
    country: "India",
    countryCode: "IN",
    city: "Delhi",
    cityCode: "DEL",
    longitude: 77.2111,
    latitude: 28.6142,
  },

  {
    sessionId: 4,
    userNo: 9,
    isSessionCreator: true,
    country: "India",
    countryCode: "IN",
    city: "Mumbai",
    cityCode: "BOM",
    longitude: 72.8777,
    latitude: 19.076,
  },

  {
    sessionId: 4,
    userNo: 10,
    isSessionCreator: false,
    country: "India",
    countryCode: "IN",
    city: "Mumbai",
    cityCode: "BOM",
    longitude: 72.8788,
    latitude: 19.0771,
  },

  // United States - Sessions
  {
    sessionId: 5,
    userNo: 11,
    isSessionCreator: true,
    country: "United States",
    countryCode: "US",
    city: "New York",
    cityCode: "NYC",
    longitude: -74.006,
    latitude: 40.7128,
  },

  {
    sessionId: 5,
    userNo: 12,
    isSessionCreator: false,
    country: "United States",
    countryCode: "US",
    city: "New York",
    cityCode: "NYC",
    longitude: -74.0071,
    latitude: 40.7139,
  },

  {
    sessionId: 6,
    userNo: 13,
    isSessionCreator: true,
    country: "United States",
    countryCode: "US",
    city: "San Francisco",
    cityCode: "SFO",
    longitude: -122.4194,
    latitude: 37.7749,
  },

  {
    sessionId: 6,
    userNo: 14,
    isSessionCreator: false,
    country: "United States",
    countryCode: "US",
    city: "San Francisco",
    cityCode: "SFO",
    longitude: -122.4172,
    latitude: 37.7735,
  },

  // United Kingdom - Sessions
  {
    sessionId: 7,
    userNo: 15,
    isSessionCreator: true,
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    cityCode: "LON",
    longitude: -0.1276,
    latitude: 51.5074,
  },

  {
    sessionId: 7,
    userNo: 16,
    isSessionCreator: false,
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    cityCode: "LON",
    longitude: -0.1254,
    latitude: 51.5081,
  },

  // Australia - Sessions
  {
    sessionId: 8,
    userNo: 17,
    isSessionCreator: true,
    country: "Australia",
    countryCode: "AU",
    city: "Sydney",
    cityCode: "SYD",
    longitude: 151.2093,
    latitude: -33.8688,
  },

  {
    sessionId: 8,
    userNo: 18,
    isSessionCreator: false,
    country: "Australia",
    countryCode: "AU",
    city: "Sydney",
    cityCode: "SYD",
    longitude: 151.2078,
    latitude: -33.8699,
  },

  // Canada - Sessions
  {
    sessionId: 9,
    userNo: 19,
    isSessionCreator: true,
    country: "Canada",
    countryCode: "CA",
    city: "Toronto",
    cityCode: "TOR",
    longitude: -79.3832,
    latitude: 43.6532,
  },

  {
    sessionId: 9,
    userNo: 20,
    isSessionCreator: false,
    country: "Canada",
    countryCode: "CA",
    city: "Toronto",
    cityCode: "TOR",
    longitude: -79.3821,
    latitude: 43.6545,
  },

  // France - Sessions
  {
    sessionId: 10,
    userNo: 21,
    isSessionCreator: true,
    country: "France",
    countryCode: "FR",
    city: "Paris",
    cityCode: "PAR",
    longitude: 2.3522,
    latitude: 48.8566,
  },

  {
    sessionId: 10,
    userNo: 22,
    isSessionCreator: false,
    country: "France",
    countryCode: "FR",
    city: "Paris",
    cityCode: "PAR",
    longitude: 2.3508,
    latitude: 48.8575,
  },

  // Germany - Sessions
  {
    sessionId: 11,
    userNo: 23,
    isSessionCreator: true,
    country: "Germany",
    countryCode: "DE",
    city: "Berlin",
    cityCode: "BER",
    longitude: 13.405,
    latitude: 52.52,
  },

  {
    sessionId: 11,
    userNo: 24,
    isSessionCreator: false,
    country: "Germany",
    countryCode: "DE",
    city: "Berlin",
    cityCode: "BER",
    longitude: 13.4041,
    latitude: 52.5212,
  },

  // Brazil - Sessions
  {
    sessionId: 12,
    userNo: 25,
    isSessionCreator: true,
    country: "Brazil",
    countryCode: "BR",
    city: "Rio de Janeiro",
    cityCode: "RIO",
    longitude: -43.1729,
    latitude: -22.9068,
  },

  {
    sessionId: 12,
    userNo: 26,
    isSessionCreator: false,
    country: "Brazil",
    countryCode: "BR",
    city: "Rio de Janeiro",
    cityCode: "RIO",
    longitude: -43.1707,
    latitude: -22.9075,
  },

  // Japan - Sessions
  {
    sessionId: 13,
    userNo: 27,
    isSessionCreator: true,
    country: "Japan",
    countryCode: "JP",
    city: "Tokyo",
    cityCode: "TYO",
    longitude: 139.6917,
    latitude: 35.6895,
  },

  {
    sessionId: 13,
    userNo: 28,
    isSessionCreator: false,
    country: "Japan",
    countryCode: "JP",
    city: "Tokyo",
    cityCode: "TYO",
    longitude: 139.6921,
    latitude: 35.6901,
  },

  // South Africa - Sessions
  {
    sessionId: 14,
    userNo: 29,
    isSessionCreator: true,
    country: "South Africa",
    countryCode: "ZA",
    city: "Cape Town",
    cityCode: "CPT",
    longitude: 18.4241,
    latitude: -33.9249,
  },

  {
    sessionId: 14,
    userNo: 30,
    isSessionCreator: false,
    country: "South Africa",
    countryCode: "ZA",
    city: "Cape Town",
    cityCode: "CPT",
    longitude: 18.4235,
    latitude: -33.9257,
  },

  // Italy - Sessions
  {
    sessionId: 15,
    userNo: 31,
    isSessionCreator: true,
    country: "Italy",
    countryCode: "IT",
    city: "Rome",
    cityCode: "ROM",
    longitude: 12.4964,
    latitude: 41.9028,
  },

  {
    sessionId: 15,
    userNo: 32,
    isSessionCreator: false,
    country: "Italy",
    countryCode: "IT",
    city: "Rome",
    cityCode: "ROM",
    longitude: 12.4971,
    latitude: 41.9035,
  },

  // Russia - Sessions
  {
    sessionId: 16,
    userNo: 33,
    isSessionCreator: true,
    country: "Russia",
    countryCode: "RU",
    city: "Moscow",
    cityCode: "MOW",
    longitude: 37.6173,
    latitude: 55.7558,
  },

  {
    sessionId: 16,
    userNo: 34,
    isSessionCreator: false,
    country: "Russia",
    countryCode: "RU",
    city: "Moscow",
    cityCode: "MOW",
    longitude: 37.6165,
    latitude: 55.7567,
  },

  // China - Sessions
  {
    sessionId: 17,
    userNo: 35,
    isSessionCreator: true,
    country: "China",
    countryCode: "CN",
    city: "Beijing",
    cityCode: "BJS",
    longitude: 116.4074,
    latitude: 39.9042,
  },

  {
    sessionId: 17,
    userNo: 36,
    isSessionCreator: false,
    country: "China",
    countryCode: "CN",
    city: "Beijing",
    cityCode: "BJS",
    longitude: 116.4081,
    latitude: 39.905,
  },
];

export const RealTimeSessionMonitoringTableData = [
  {
    sessionId: 12839712893712,
    participants: 8,
    sessionType: "Standard",
    location: "Brazil",
    locationCode: "BR",
    duration: "1h 12m 04s",
  },
  {
    sessionId: 18475692345981,
    participants: 3,
    sessionType: "Secure",
    location: "Germany",
    locationCode: "DE",
    duration: "0h 45m 33s",
  },
  {
    sessionId: 12938475672938,
    participants: 5,
    sessionType: "Wallet",
    location: "Japan",
    locationCode: "JP",
    duration: "2h 11m 21s",
  },
  {
    sessionId: 12783456923875,
    participants: 9,
    sessionType: "Standard",
    location: "India",
    locationCode: "IN",
    duration: "1h 05m 47s",
  },
  {
    sessionId: 13849576283947,
    participants: 7,
    sessionType: "Secure",
    location: "USA",
    locationCode: "US",
    duration: "1h 30m 12s",
  },
  {
    sessionId: 19847562938475,
    participants: 4,
    sessionType: "Wallet",
    location: "France",
    locationCode: "FR",
    duration: "1h 18m 50s",
  },
  {
    sessionId: 12837456928374,
    participants: 6,
    sessionType: "Standard",
    location: "Australia",
    locationCode: "AU",
    duration: "2h 05m 40s",
  },
  {
    sessionId: 12938475623485,
    participants: 10,
    sessionType: "Secure",
    location: "Brazil",
    locationCode: "BR",
    duration: "1h 50m 30s",
  },
  {
    sessionId: 19837465982347,
    participants: 2,
    sessionType: "Wallet",
    location: "Germany",
    locationCode: "DE",
    duration: "0h 38m 15s",
  },
  {
    sessionId: 12839475692834,
    participants: 1,
    sessionType: "Standard",
    location: "Japan",
    locationCode: "JP",
    duration: "0h 59m 05s",
  },
  {
    sessionId: 13984756239485,
    participants: 8,
    sessionType: "Secure",
    location: "India",
    locationCode: "IN",
    duration: "1h 25m 12s",
  },
  {
    sessionId: 12398475628347,
    participants: 7,
    sessionType: "Wallet",
    location: "USA",
    locationCode: "US",
    duration: "1h 10m 43s",
  },
  {
    sessionId: 12783945692834,
    participants: 9,
    sessionType: "Standard",
    location: "France",
    locationCode: "FR",
    duration: "1h 35m 55s",
  },
  {
    sessionId: 13849576238947,
    participants: 6,
    sessionType: "Secure",
    location: "Australia",
    locationCode: "AU",
    duration: "2h 12m 25s",
  },
  {
    sessionId: 19873456928374,
    participants: 5,
    sessionType: "Wallet",
    location: "Brazil",
    locationCode: "BR",
    duration: "1h 45m 33s",
  },
  {
    sessionId: 12938475623489,
    participants: 3,
    sessionType: "Standard",
    location: "Germany",
    locationCode: "DE",
    duration: "0h 50m 20s",
  },
  {
    sessionId: 19837465982348,
    participants: 10,
    sessionType: "Secure",
    location: "Japan",
    locationCode: "JP",
    duration: "2h 01m 10s",
  },
  {
    sessionId: 12839475692835,
    participants: 2,
    sessionType: "Wallet",
    location: "India",
    locationCode: "IN",
    duration: "0h 42m 55s",
  },
  {
    sessionId: 13984756239486,
    participants: 4,
    sessionType: "Standard",
    location: "USA",
    locationCode: "US",
    duration: "1h 15m 37s",
  },
  {
    sessionId: 12398475628348,
    participants: 1,
    sessionType: "Secure",
    location: "France",
    locationCode: "FR",
    duration: "0h 55m 28s",
  },
];
